#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX 

bspc config border_width         1
bspc config window_gap          10
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications
sxhkd -c ~/.config/sxhkd/sxhkdrc &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
bash ~/.config/polybar/launch.sh --shapes
